### ISSUE TITLE
DP : week 3 : Quiz: Huffman Codes 

### ISSUE THREAD

**Issue by Pj-develop** [Bhanupriya-art/CSE408-Coursera-Answers#2]
![Week3](https://github.com/Bhanupriya-art/CSE408-Coursera-Answers/assets/110783469/cec8abff-4cde-471c-ba6d-4c81622af3c1)

**Comment by 07Sushant** [comment]
### Dynamic Programming, Greedy Algorithms-  **ALL MCQ FULL MARKS**   **100% Score**

![qu](https://github.com/Bhanupriya-art/CSE408-Coursera-Answers/assets/93951120/2daaef3c-d480-4598-8fd1-8e47799172dc)

https://youtu.be/WwdVhN4lPDA?si=2XCgFsdN8Hj6nr6d
https://youtube.com/shorts/q0apdyEufXk?si=Aeu5Nj3lUlIbfKg6

### Dynamic Programming, Greedy Algorithms-  **ALL Programming Assessment**  **100% Score**

![image](https://github.com/Bhanupriya-art/CSE408-Coursera-Answers/assets/93951120/9f03ac6c-e1fc-4822-83f5-6b7a9a8a4f41)

**Comment by 07Sushant** [comment]
# <div align="center">Dynamic Programming, Greedy Algorithms</div>
### <div align="center">University of Colorado BoulderAll Assignments
</div>

## <div align="center">YouTube</div>
###### <div align="center">Click on the image</div>

[![Screenshot 2024-03-13 021919](https://github.com/Bhanupriya-art/CSE408-Coursera-Answers/assets/93951120/ec26e536-8886-43ce-952e-8de4dfd3359e)](https://www.youtube.com/@07Sushant)



<br>
Check out YouTube channel for video content related to our programming assessments!



<br>

## [Week 1](https://github.com/07Sushant/Design-Analysis-and-Algorithm/tree/main/Dynamic%20Programming%2C%20Greedy%20Algorithms/Week%201)

### Programming Assessment
- [Link to Week 1 Programming Assessment](https://github.com/07Sushant/Design-Analysis-and-Algorithm/blob/main/Dynamic%20Programming%2C%20Greedy%20Algorithms/Week%201/README.md)

## [Week 2](https://github.com/07Sushant/Design-Analysis-and-Algorithm/tree/main/Dynamic%20Programming%2C%20Greedy%20Algorithms/Week%202)

### Programming Assessment
- [Link to Week 2 Programming Assessment](https://github.com/07Sushant/Design-Analysis-and-Algorithm/blob/main/Dynamic%20Programming%2C%20Greedy%20Algorithms/Week%202/README.md)

## [Week 3](https://github.com/07Sushant/Design-Analysis-and-Algorithm/tree/main/Dynamic%20Programming%2C%20Greedy%20Algorithms/Week%203)

### Programming Assessment
- [Link to Week 3 Programming Assessment](https://github.com/07Sushant/Design-Analysis-and-Algorithm/blob/main/Dynamic%20Programming%2C%20Greedy%20Algorithms/Week%203/README.md)

## [Week 4](https://github.com/07Sushant/Design-Analysis-and-Algorithm/tree/main/Dynamic%20Programming%2C%20Greedy%20Algorithms/Week%204)

### Programming Assessment
- [Link to Week 4 Programming Assessment](https://github.com/07Sushant/Design-Analysis-and-Algorithm/blob/main/Dynamic%20Programming%2C%20Greedy%20Algorithms/Week%204/README.md)
